version: "3.8"
services:
  app:
    build: .
    environment:
      - CONSUMER_KEY=${CONSUMER_KEY}
      - CONSUMER_SECRET=${CONSUMER_SECRET}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - TWEET_QUERY=@prinz_flex
      - SERVICE_PORT=8000
      - DEBUG=True
    ports:
      - "8000:8000"
